import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1728624246351 implements MigrationInterface {
    name = 'Migration1728624246351'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "delivery_order_subscription_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "delivery_order_courier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "customer_family_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP CONSTRAINT "service_pricing_wasteserviceid_fkey"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "subscription_company_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "subscription_family_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "waste_service_items_pickupitempickupitemid_fkey"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "waste_service_items_servicepricingid_fkey"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "waste_service_days_pickupdaypickupdayid_fkey"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "waste_service_days_servicepricingid_fkey"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "subscription_services_servicepricingid_fkey"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "subscription_services_subscriptionid_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16468_sqlite_autoindex_customer_2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16463_sqlite_autoindex_subscription_3"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16463_sqlite_autoindex_subscription_2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16443_sqlite_autoindex_waste_service_items_1"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16443_idx_182b9ab23579729b9c97901531"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16443_idx_b41e641a2c8573e4b9da1b3589"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16438_sqlite_autoindex_waste_service_days_1"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16438_idx_c1be1b6eef1e69de9a2efc2c69"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16438_idx_28ae5d6ff159010a5fd5efb515"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16448_idx_2b2ee890e664ac6d23df3cd297"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16448_idx_1887827c207f3f22db8d9650c2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16448_sqlite_autoindex_subscription_services_1"`);
        await queryRunner.query(`CREATE TABLE "pickupDays_placePickup" ("pickupDayPickupDayId" integer NOT NULL, "placePickupPlacePickupId" integer NOT NULL, CONSTRAINT "PK_a1072a98bc89c19aca728f6fdc5" PRIMARY KEY ("pickupDayPickupDayId", "placePickupPlacePickupId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9778feb4633286d53c5f35820d" ON "pickupDays_placePickup" ("pickupDayPickupDayId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39a4a704af59461e877d5e7e16" ON "pickupDays_placePickup" ("placePickupPlacePickupId") `);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP CONSTRAINT "idx_16404_place_pickup_pkey" CASCADE`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "placePickup_Id"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP COLUMN "pickupItempickupItemId"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "placePickup_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD CONSTRAINT "PK_694292ad14c6721af6e656567f4" PRIMARY KEY ("placePickup_id")`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "isComposable" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD "pickupItemPickupItemId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_182b9ab23579729b9c979015315" PRIMARY KEY ("pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_182b9ab23579729b9c979015315"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb" PRIMARY KEY ("servicePricingId", "pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f" PRIMARY KEY ("servicePricingId", "pickupDayPickupDayId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_4c436455f74bf9a81536e321c77" PRIMARY KEY ("subscriptionId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "idx_16473_sqlite_autoindex_company_1"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "name" character varying NOT NULL DEFAULT 'Default Company Name'`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "ruc"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "ruc" integer`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "industry"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "industry" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "reference" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "owner_name" character varying`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "customId" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP CONSTRAINT "idx_16458_sqlite_autoindex_courier_1"`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "courier" ADD CONSTRAINT "PK_94613ec7dc72f7dfa2d072a31cf" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "name" character varying NOT NULL DEFAULT 'courier name'`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "mother_last_name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "mother_last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "document_identity"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "document_identity" integer`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "refAddress"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "refAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "idx_16478_sqlite_autoindex_delivery_order_1"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "PK_08f144cd9889759426ab37c358e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "date_received"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "date_received" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "waste_weight" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "waste_weight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "compost"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "compost" integer`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "peso_balde" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "subscription_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "subscription_id" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "courier_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "courier_id" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "idx_16468_sqlite_autoindex_customer_1"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "customer_id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "PK_cde3d123fc6077bcd75eb051226" PRIMARY KEY ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "firebaseUid"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "firebaseUid" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_0aaab4b50a83b712071d58c5d46" UNIQUE ("firebaseUid")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "name" character varying NOT NULL DEFAULT 'customer name'`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "document_identity"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "document_identity" integer`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "mother_last_name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "mother_last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "customId" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "family_id" character varying`);
        await queryRunner.query(`ALTER TABLE "family" DROP CONSTRAINT "idx_16417_sqlite_autoindex_family_1"`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "family_id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "family" ADD CONSTRAINT "PK_ccfeee590e2ffbbb242511b26bf" PRIMARY KEY ("family_id")`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "name" character varying NOT NULL DEFAULT 'family name'`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "address" character varying NOT NULL DEFAULT 'Default address'`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "reference" character varying`);
        await queryRunner.query(`ALTER TABLE "family" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "customId" character varying`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "reference" character varying`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "latitude" integer`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "longitude" integer`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP CONSTRAINT "idx_16411_pickup_day_pkey" CASCADE`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "pickupDay_id"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "pickupDay_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD CONSTRAINT "PK_fd25efb2532ec7748413c5a7f74" PRIMARY KEY ("pickupDay_id")`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "dayOfWeek"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "dayOfWeek" character varying`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ALTER COLUMN "isAllDay" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "startTime" integer`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "endTime" integer`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP CONSTRAINT "idx_16397_pickup_item_pkey"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "pickupItem_id"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "pickupItem_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD CONSTRAINT "PK_bf80d80c85612729c1690513349" PRIMARY KEY ("pickupItem_id")`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP CONSTRAINT "idx_16453_sqlite_autoindex_waste_service_1"`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD CONSTRAINT "PK_59630e0a502e6d34da983ea2aaf" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "name" character varying NOT NULL DEFAULT 'waste service'`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "clientType"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "clientType" character varying`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP CONSTRAINT "idx_16484_sqlite_autoindex_service_pricing_1"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD CONSTRAINT "PK_a9d4b6cf683e43141affcc43964" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "price" integer NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "frequency"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "frequency" integer`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "oneTimePrice"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "oneTimePrice" integer`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "isAddon"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "isAddon" integer`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "wasteServiceId"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "wasteServiceId" character varying`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "idx_16463_sqlite_autoindex_subscription_1"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "id" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "startDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "endDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "baldes"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "baldes" integer`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "family_id" character varying`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "UQ_d70cc5c53f80de6e354891fcd11" UNIQUE ("family_id")`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "company_id" character varying`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "UQ_040d4d92b5bf63a5406f9be65e2" UNIQUE ("company_id")`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP CONSTRAINT "idx_16423_sqlite_autoindex_neighborhood_1"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD CONSTRAINT "PK_97797961be30242a5170d17caec" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP CONSTRAINT "idx_16429_payment_method_pkey"`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "idx_16390_district_pkey"`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "district_id"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "district_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "PK_d13cbacbdeab4c466c8c8dadd5d" PRIMARY KEY ("district_id")`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "name" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "postalCode" character varying`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_182b9ab23579729b9c979015315" PRIMARY KEY ("pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD "servicePricingId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_182b9ab23579729b9c979015315"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb" PRIMARY KEY ("pickupItemPickupItemId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_c1be1b6eef1e69de9a2efc2c693" PRIMARY KEY ("pickupDayPickupDayId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD "servicePricingId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_c1be1b6eef1e69de9a2efc2c693"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f" PRIMARY KEY ("pickupDayPickupDayId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_28ae5d6ff159010a5fd5efb5159" PRIMARY KEY ("servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP COLUMN "pickupDayPickupDayId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD "pickupDayPickupDayId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_28ae5d6ff159010a5fd5efb5159"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f" PRIMARY KEY ("servicePricingId", "pickupDayPickupDayId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_4c436455f74bf9a81536e321c77"`);
        // await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_1887827c207f3f22db8d9650c2f" PRIMARY KEY ("servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP COLUMN "subscriptionId"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD "subscriptionId" character varying NOT NULL DEFAULT gen_random_uuid()`);
        // await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_1887827c207f3f22db8d9650c2f"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_4c436455f74bf9a81536e321c77" PRIMARY KEY ("servicePricingId", "subscriptionId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_4c436455f74bf9a81536e321c77"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_2b2ee890e664ac6d23df3cd2978" PRIMARY KEY ("subscriptionId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD "servicePricingId" character varying NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_2b2ee890e664ac6d23df3cd2978"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_4c436455f74bf9a81536e321c77" PRIMARY KEY ("subscriptionId", "servicePricingId")`);
        await queryRunner.query(`CREATE INDEX "IDX_b41e641a2c8573e4b9da1b3589" ON "waste_service_items" ("servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_182b9ab23579729b9c97901531" ON "waste_service_items" ("pickupItemPickupItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28ae5d6ff159010a5fd5efb515" ON "waste_service_days" ("servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1be1b6eef1e69de9a2efc2c69" ON "waste_service_days" ("pickupDayPickupDayId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b2ee890e664ac6d23df3cd297" ON "subscription_services" ("subscriptionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1887827c207f3f22db8d9650c2" ON "subscription_services" ("servicePricingId") `);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "FK_dbc63f0d3d38f0d634ae9898758" FOREIGN KEY ("subscription_id") REFERENCES "subscription"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "FK_7e51aeee1a9c2f845ad3ffe5858" FOREIGN KEY ("courier_id") REFERENCES "courier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_4da2b83be276e342edd06540aad" FOREIGN KEY ("family_id") REFERENCES "family"("family_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD CONSTRAINT "FK_58d40ad131efcf8e0666c8eb162" FOREIGN KEY ("wasteServiceId") REFERENCES "waste_service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_d70cc5c53f80de6e354891fcd11" FOREIGN KEY ("family_id") REFERENCES "family"("family_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_040d4d92b5bf63a5406f9be65e2" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pickupDays_placePickup" ADD CONSTRAINT "FK_9778feb4633286d53c5f35820dc" FOREIGN KEY ("pickupDayPickupDayId") REFERENCES "pickup_day"("pickupDay_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pickupDays_placePickup" ADD CONSTRAINT "FK_39a4a704af59461e877d5e7e16a" FOREIGN KEY ("placePickupPlacePickupId") REFERENCES "place_pickup"("placePickup_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "FK_b41e641a2c8573e4b9da1b35899" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "FK_182b9ab23579729b9c979015315" FOREIGN KEY ("pickupItemPickupItemId") REFERENCES "pickup_item"("pickupItem_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "FK_28ae5d6ff159010a5fd5efb5159" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "FK_c1be1b6eef1e69de9a2efc2c693" FOREIGN KEY ("pickupDayPickupDayId") REFERENCES "pickup_day"("pickupDay_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "FK_2b2ee890e664ac6d23df3cd2978" FOREIGN KEY ("subscriptionId") REFERENCES "subscription"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        // await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "FK_1887827c207f3f22db8d9650c2f" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "FK_1887827c207f3f22db8d9650c2f"`);
        // await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "FK_2b2ee890e664ac6d23df3cd2978"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "FK_c1be1b6eef1e69de9a2efc2c693"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "FK_28ae5d6ff159010a5fd5efb5159"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "FK_182b9ab23579729b9c979015315"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "FK_b41e641a2c8573e4b9da1b35899"`);
        await queryRunner.query(`ALTER TABLE "pickupDays_placePickup" DROP CONSTRAINT "FK_39a4a704af59461e877d5e7e16a"`);
        await queryRunner.query(`ALTER TABLE "pickupDays_placePickup" DROP CONSTRAINT "FK_9778feb4633286d53c5f35820dc"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_040d4d92b5bf63a5406f9be65e2"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_d70cc5c53f80de6e354891fcd11"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP CONSTRAINT "FK_58d40ad131efcf8e0666c8eb162"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_4da2b83be276e342edd06540aad"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "FK_7e51aeee1a9c2f845ad3ffe5858"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "FK_dbc63f0d3d38f0d634ae9898758"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1887827c207f3f22db8d9650c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b2ee890e664ac6d23df3cd297"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1be1b6eef1e69de9a2efc2c69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28ae5d6ff159010a5fd5efb515"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_182b9ab23579729b9c97901531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b41e641a2c8573e4b9da1b3589"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_4c436455f74bf9a81536e321c77"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_2b2ee890e664ac6d23df3cd2978" PRIMARY KEY ("subscriptionId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD "servicePricingId" text`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_2b2ee890e664ac6d23df3cd2978"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_4c436455f74bf9a81536e321c77" PRIMARY KEY ("servicePricingId", "subscriptionId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_4c436455f74bf9a81536e321c77"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_1887827c207f3f22db8d9650c2f" PRIMARY KEY ("servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP COLUMN "subscriptionId"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD "subscriptionId" text`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_1887827c207f3f22db8d9650c2f"`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "PK_4c436455f74bf9a81536e321c77" PRIMARY KEY ("subscriptionId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_28ae5d6ff159010a5fd5efb5159" PRIMARY KEY ("servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP COLUMN "pickupDayPickupDayId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD "pickupDayPickupDayId" bigint`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_28ae5d6ff159010a5fd5efb5159"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f" PRIMARY KEY ("pickupDayPickupDayId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_c1be1b6eef1e69de9a2efc2c693" PRIMARY KEY ("pickupDayPickupDayId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD "servicePricingId" text`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_c1be1b6eef1e69de9a2efc2c693"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f" PRIMARY KEY ("pickupDayPickupDayId", "servicePricingId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_182b9ab23579729b9c979015315" PRIMARY KEY ("pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP COLUMN "servicePricingId"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD "servicePricingId" text`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_182b9ab23579729b9c979015315"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb" PRIMARY KEY ("servicePricingId", "pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "postalCode" text`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "PK_d13cbacbdeab4c466c8c8dadd5d"`);
        await queryRunner.query(`ALTER TABLE "district" DROP COLUMN "district_id"`);
        await queryRunner.query(`ALTER TABLE "district" ADD "district_id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "idx_16390_district_pkey" PRIMARY KEY ("district_id")`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a"`);
        await queryRunner.query(`ALTER TABLE "payment_method" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_method" ADD CONSTRAINT "idx_16429_payment_method_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP CONSTRAINT "PK_97797961be30242a5170d17caec"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "neighborhood" ADD CONSTRAINT "idx_16423_sqlite_autoindex_neighborhood_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "UQ_040d4d92b5bf63a5406f9be65e2"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "company_id" text`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "UQ_d70cc5c53f80de6e354891fcd11"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "family_id" text`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "baldes"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "baldes" bigint`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "status" text`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "endDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "startDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "idx_16463_sqlite_autoindex_subscription_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "wasteServiceId"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "wasteServiceId" text`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "isAddon"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "isAddon" bigint`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "oneTimePrice"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "oneTimePrice" bigint`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "frequency"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "frequency" bigint`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "price" bigint`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP CONSTRAINT "PK_a9d4b6cf683e43141affcc43964"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD CONSTRAINT "idx_16484_sqlite_autoindex_service_pricing_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "clientType"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "clientType" text`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP CONSTRAINT "PK_59630e0a502e6d34da983ea2aaf"`);
        await queryRunner.query(`ALTER TABLE "waste_service" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "waste_service" ADD CONSTRAINT "idx_16453_sqlite_autoindex_waste_service_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP CONSTRAINT "PK_bf80d80c85612729c1690513349"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" DROP COLUMN "pickupItem_id"`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD "pickupItem_id" bigint NOT NULL DEFAULT nextval('pickup_item_pickupitem_id_seq')`);
        await queryRunner.query(`ALTER TABLE "pickup_item" ADD CONSTRAINT "idx_16397_pickup_item_pkey" PRIMARY KEY ("pickupItem_id")`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "endTime"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "endTime" bigint`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "startTime"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "startTime" bigint`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ALTER COLUMN "isAllDay" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "dayOfWeek"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "dayOfWeek" text`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP CONSTRAINT "PK_fd25efb2532ec7748413c5a7f74"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" DROP COLUMN "pickupDay_id"`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD "pickupDay_id" bigint NOT NULL DEFAULT nextval('pickup_day_pickupday_id_seq')`);
        await queryRunner.query(`ALTER TABLE "pickup_day" ADD CONSTRAINT "idx_16411_pickup_day_pkey" PRIMARY KEY ("pickupDay_id")`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "longitude"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "longitude" bigint`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "latitude"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "latitude" bigint`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "reference" text`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "customId" text`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "family" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "reference" text`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "address" text DEFAULT 'Default address'`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "family" DROP CONSTRAINT "PK_ccfeee590e2ffbbb242511b26bf"`);
        await queryRunner.query(`ALTER TABLE "family" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "family" ADD "family_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "family" ADD CONSTRAINT "idx_16417_sqlite_autoindex_family_1" PRIMARY KEY ("family_id")`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "family_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "family_id" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "customId" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phoneNumber" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "mother_last_name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "mother_last_name" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "document_identity"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "document_identity" bigint`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_0aaab4b50a83b712071d58c5d46"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "firebaseUid"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "firebaseUid" text`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "PK_cde3d123fc6077bcd75eb051226"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "customer_id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "idx_16468_sqlite_autoindex_customer_1" PRIMARY KEY ("customer_id")`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "courier_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "courier_id" text`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "subscription_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "subscription_id" text`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "peso_balde" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "compost"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "compost" bigint`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "waste_weight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ALTER COLUMN "waste_weight" TYPE double precision`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "date_received"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "date_received" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP CONSTRAINT "PK_08f144cd9889759426ab37c358e"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "idx_16478_sqlite_autoindex_delivery_order_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "refAddress"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "refAddress" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "phoneNumber" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "document_identity"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "document_identity" bigint`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "mother_last_name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "mother_last_name" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "courier" DROP CONSTRAINT "PK_94613ec7dc72f7dfa2d072a31cf"`);
        await queryRunner.query(`ALTER TABLE "courier" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "courier" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "courier" ADD CONSTRAINT "idx_16458_sqlite_autoindex_courier_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "customId"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "customId" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "owner_name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "owner_name" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "reference"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "reference" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "industry"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "industry" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "phoneNumber" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "ruc"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "ruc" bigint`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "name" text`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20"`);
        await queryRunner.query(`ALTER TABLE "company" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "idx_16473_sqlite_autoindex_company_1" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subscription_services" DROP CONSTRAINT "PK_4c436455f74bf9a81536e321c77"`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" DROP CONSTRAINT "PK_8cfe54d2d09d971dcc0c8feee8f"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_40e7330afb1e222bc4cf5ea37cb"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "PK_182b9ab23579729b9c979015315" PRIMARY KEY ("pickupItemPickupItemId")`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP CONSTRAINT "PK_182b9ab23579729b9c979015315"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" DROP COLUMN "pickupItemPickupItemId"`);
        await queryRunner.query(`ALTER TABLE "service_pricing" DROP COLUMN "isComposable"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP CONSTRAINT "PK_694292ad14c6721af6e656567f4"`);
        await queryRunner.query(`ALTER TABLE "place_pickup" DROP COLUMN "placePickup_id"`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD "pickupItempickupItemId" bigint`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD "placePickup_Id" bigint NOT NULL DEFAULT nextval('place_pickup_placepickup_id_seq')`);
        await queryRunner.query(`ALTER TABLE "place_pickup" ADD CONSTRAINT "idx_16404_place_pickup_pkey" PRIMARY KEY ("placePickup_Id")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39a4a704af59461e877d5e7e16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9778feb4633286d53c5f35820d"`);
        await queryRunner.query(`DROP TABLE "pickupDays_placePickup"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16448_sqlite_autoindex_subscription_services_1" ON "subscription_services" ("servicePricingId", "subscriptionId") `);
        await queryRunner.query(`CREATE INDEX "idx_16448_idx_1887827c207f3f22db8d9650c2" ON "subscription_services" ("servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "idx_16448_idx_2b2ee890e664ac6d23df3cd297" ON "subscription_services" ("subscriptionId") `);
        await queryRunner.query(`CREATE INDEX "idx_16438_idx_28ae5d6ff159010a5fd5efb515" ON "waste_service_days" ("servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "idx_16438_idx_c1be1b6eef1e69de9a2efc2c69" ON "waste_service_days" ("pickupDayPickupDayId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16438_sqlite_autoindex_waste_service_days_1" ON "waste_service_days" ("pickupDayPickupDayId", "servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "idx_16443_idx_b41e641a2c8573e4b9da1b3589" ON "waste_service_items" ("servicePricingId") `);
        await queryRunner.query(`CREATE INDEX "idx_16443_idx_182b9ab23579729b9c97901531" ON "waste_service_items" ("pickupItempickupItemId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16443_sqlite_autoindex_waste_service_items_1" ON "waste_service_items" ("pickupItempickupItemId", "servicePricingId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16463_sqlite_autoindex_subscription_2" ON "subscription" ("company_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16463_sqlite_autoindex_subscription_3" ON "subscription" ("family_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16468_sqlite_autoindex_customer_2" ON "customer" ("firebaseUid") `);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "subscription_services_subscriptionid_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "subscription"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "subscription_services" ADD CONSTRAINT "subscription_services_servicepricingid_fkey" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "waste_service_days_servicepricingid_fkey" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "waste_service_days" ADD CONSTRAINT "waste_service_days_pickupdaypickupdayid_fkey" FOREIGN KEY ("pickupDayPickupDayId") REFERENCES "pickup_day"("pickupDay_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "waste_service_items_servicepricingid_fkey" FOREIGN KEY ("servicePricingId") REFERENCES "service_pricing"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "waste_service_items" ADD CONSTRAINT "waste_service_items_pickupitempickupitemid_fkey" FOREIGN KEY ("pickupItempickupItemId") REFERENCES "pickup_item"("pickupItem_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "subscription_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "family"("family_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "subscription_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_pricing" ADD CONSTRAINT "service_pricing_wasteserviceid_fkey" FOREIGN KEY ("wasteServiceId") REFERENCES "waste_service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "customer_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "family"("family_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_courier_id_fkey" FOREIGN KEY ("courier_id") REFERENCES "courier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_order" ADD CONSTRAINT "delivery_order_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "subscription"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
