name: Deploy NestJS App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build application
              run: pnpm run build

            # - name: Run tests
            #   run: pnpm test

            - name: Deploy and run migrations
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    source ~/.bashrc
                    
                    # Navigate to project directory
                    cd /var/www/nestjs-app
                    
                    # Pull latest changes
                    git pull
                    
                    # Update environment variables
                    echo "POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}'" > .env.production
                    echo "POSTGRES_USER='${{ secrets.POSTGRES_USER }}'" >> .env.production
                    echo "POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'" >> .env.production
                    echo "POSTGRES_DB='${{ secrets.POSTGRES_DB }}'" >> .env.production
                    echo "POSTGRES_PORT='${{ secrets.POSTGRES_PORT }}'" >> .env.production

                    # Set production environment
                    export NODE_ENV=production
                    
                    # Install dependencies including devDependencies needed for migrations
                    pnpm install --include=dev
                    
                    # Build the application
                    pnpm run build

                    # Run TypeORM migrations with ts-node configuration
                    echo "Running database migrations..."
                    NODE_ENV=production npx ts-node --require tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run -d src/config/datasource.ts

                    # Verify migrations status (optional)
                    NODE_ENV=production npx ts-node --require tsconfig-paths/register ./node_modules/typeorm/cli.js migration:show -d src/config/datasource.ts
                    
                    # Clean up dev dependencies after migrations
                    pnpm install --prod
                    
                    # Restart or start the application using PM2
                    pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
                  EOF
