name: CI/CD Pipeline
run-name: Main CI / CD Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            node-cache: ${{ steps.node-cache.outputs.cache-hit }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              id: node-setup
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.0.0

            - name: Cache pnpm modules
              id: node-cache
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: pnpm install

            - name: Run lint
              run: pnpm run lint

    unit_tests:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # Actualizado a la versi贸n v4

            - name: Set up Node.js
              uses: actions/setup-node@v4 # Actualizado a la versi贸n v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: pnpm install

            - name: Run unit tests
              run: pnpm run test

    build:
        runs-on: ubuntu-latest
        needs: [unit_tests]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # Actualizado a la versi贸n v4

            - name: Set up Node.js
              uses: actions/setup-node@v4 # Actualizado a la versi贸n v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm run build

            - name: Upload artifact
              if: success()
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/
