name: Run Database Migrations

on:
    workflow_dispatch:

jobs:
    migrations:
        runs-on: ubuntu-latest

        steps:
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Run migrations on Droplet
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    cd /var/www/nestjs-app
                    pnpm run migrations:run
                  EOF
