name: Migrations

on:
    push:
        branches: [main]

jobs:
    migration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Deploy and run migrations
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
                    export NVM_DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    source ~/.bashrc
                    
                    # Navigate to project directory
                    cd /var/www/nestjs-app
                    
                    # Pull latest changes
                    git pull
                    
                    # Update environment variables
                    echo "POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}'" > .env.development
                    echo "POSTGRES_USER='${{ secrets.POSTGRES_USER }}'" >> .env.development
                    echo "POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'" >> .env.development
                    echo "POSTGRES_DB='${{ secrets.POSTGRES_DB }}'" >> .env.development
                    echo "POSTGRES_PORT='${{ secrets.POSTGRES_PORT }}'" >> .env.development

                    
                    # Install dependencies including devDependencies needed for migrations
                    pnpm install 

                    # Show Migrations
                    echo "Show database migrations"
                    pnpm run migration:show

                    # Run Migrations
                    echo "Running database migrations..."
                    pnpm run migration:run

                  EOF
